### ISSUE TITLE
PyQt4 python problem

### ISSUE THREAD

**Issue by Brody404** [savio-code/fern-wifi-cracker#122]
Hello everyone,
I'm on kali linux and I have a problem when I launch fern-wifi-cracker.
I never launched it before so i don't know why i could have this problem.
Does anyone could help me please ? It will be really appreciated :)
I got this error :
```
Traceback (most recent call last):
  File "execute.py", line 8, in <module>
    from PyQt4 import QtGui,QtCore
ImportError: /usr/lib/python2.7/dist-packages/PyQt4/QtGui.x86_64-linux-gnu.so: undefined symbol: _ZN15QSessionManager16staticMetaObjectE

```

**Comment by savio-code** [comment]
This is a version mismatch of PyQt4.

Please try reinstalling pyqt like this:

apt-get install --reinstall python-qt4

**Comment by Brody404** [comment]
Hi and thx for the reply ! :grinning:
Well indeed, I did reinstall PyQt4 as you told me but I still have the same error :/
Do you think it may be because of my OS or should I reinstall PyQt4 manually ?

**Comment by Brody404** [comment]
Done, thanks you

**Comment by snipe-name** [comment]
i did evrything but i still got Traceback (most recent call last):
  File "execute.py", line 41, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: libQt5Core.so.5: cannot open shared object file: No such file or directory
can you help me

**Comment by ny2357113** [comment]
Hello I'm using kali on windows subsystem for linux and i've got the same problem as @snipe-name .
Are any of  you using WSL because maybe that is the cause...

**Comment by adon25378** [comment]
I am getting same problem

**Comment by patouch66** [comment]
execut in terminal : python /usr/share/fern-wifi-cracker/execute.py

**Comment by imnotpwnd** [comment]
> execut in terminal : python /usr/share/fern-wifi-cracker/execute.py

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
