### ISSUE TITLE
ImportError: cannot import name QtWebKit

### ISSUE THREAD

**Issue by eldipablo** [savio-code/fern-wifi-cracker#123]
Getting this when trying to run execute.py in Ubuntu 18.04:

Traceback (most recent call last):
  File "./execute.py", line 73, in <module>
    from core import *
  File "/opt/Fern-Wifi-Cracker/core/fern.py", line 15, in <module>
    from wep import *
  File "/opt/Fern-Wifi-Cracker/core/wep.py", line 2, in <module>
    from core.tools import*
  File "/opt/Fern-Wifi-Cracker/core/tools.py", line 6, in <module>
    from gui.geotrack import *
  File "/opt/Fern-Wifi-Cracker/gui/geotrack.py", line 211, in <module>
    from PyQt4 import QtWebKit
ImportError: cannot import name QtWebKit

**Comment by lejurassien** [comment]
Sadly i have the saame problem, have you maybe found a solution ?? I hope so ....

thank you
