### ISSUE TITLE
Fern stuck after selecting the wireless interface

### ISSUE THREAD

**Issue by optiimusprime** [savio-code/fern-wifi-cracker#140]
Hi,

Background information

Kali Linux 2020.2 (on VMWare workstation 15.5)
Fern version 3
Python 3.8.3
USB wireless adapter Alfa AWUS036ACH updated drivers and in monitor mode (VMWare USB compatibility mode is USB version 2.0)

Issue

After running Fer and selecting wlan0, the green circle keeps spinning like it's frozen and unusable

Running fern using python 3 throws out below errors

xeno@kali:/usr/share/fern-wifi-cracker$ sudo python3 execute.py
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 758, resource id: 10640312, major code: 40 (TranslateCoords), minor code: 0
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/fern-wifi-cracker/core/fern.py", line 520, in set_monitor_thread
    interfaces = regex.findall(monitor_interface_process)
AttributeError: 'object' object has no attribute 'findall'

Any ideas are greatly appreciated.

**Comment by DucNguyen1982** [comment]
I have same error like that, any solution to solve that errror , please advice me, team, Thank
#fern-wifi-cracker 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
libpng warning: iCCP: known incorrect sRGB profile

**Comment by neve7mind** [comment]
Hi, just want to make sure. What is your output of `iwconfig` command?
