### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by datuanho2k9** [savio-code/fern-wifi-cracker#153]
I'm using Kali Linux on WSL and I get the following error:
```
Traceback (most recent call last):
  File "/usr/share/fern-wifi-cracker/execute.py", line 41, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: libQt5Core.so.5: cannot open shared object file: No such file or directory
```

I tried to install the prerequisites again but still have the error.
Please help me, thanks.

**Comment by MRXUSERx** [comment]
Traceback (most recent call last):
  File "/usr/share/fern-wifi-cracker/execute.py", line 41, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: libQt5Core.so.5: cannot open shared object file: No such file or directory

**Comment by MRXUSERx** [comment]
me too
help
