### ISSUE TITLE
App Not Executing - Reinstalled, updated

### ISSUE THREAD

**Issue by varun-vik** [savio-code/fern-wifi-cracker#159]
Not able to execute the app. "Sudo fern-wifi-cracker" shows this error. App was running till yesterday but wasn't showing any APs.

Bad key pcolormesh.snap in file /usr/share/matplotlib/mpl-data/matplotlibrc, line 134 ('pcolormesh.snap: True  # Whether to snap the mesh to pixel boundaries. This is')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution

Bad key axes.zmargin in file /usr/share/matplotlib/mpl-data/matplotlibrc, line 417 ('axes.zmargin:   .05  # z margin.  See `axes.Axes.margins`')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution

Bad key date.converter in file /usr/share/matplotlib/mpl-data/matplotlibrc, line 455 ('date.converter:                  auto')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution

Bad key date.interval_multiples in file /usr/share/matplotlib/mpl-data/matplotlibrc, line 457 ('date.interval_multiples:         True')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution

Bad key xtick.labelcolor in file /usr/share/matplotlib/mpl-data/matplotlibrc, line 474 ('xtick.labelcolor:    inherit # color of the tick labels or inherit from xtick.color')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution

Bad key ytick.labelcolor in file /usr/share/matplotlib/mpl-data/matplotlibrc, line 495 ('ytick.labelcolor:    inherit # color of the tick labels or inherit from ytick.color')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution

Bad key legend.labelcolor in file /usr/share/matplotlib/mpl-data/matplotlibrc, line 530 ('legend.labelcolor:    None')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution
Traceback (most recent call last):
  File "/usr/share/fern-wifi-cracker/execute.py", line 107, in <module>
    from core import *
  File "/usr/share/fern-wifi-cracker/core/fern.py", line 15, in <module>
    from core.wep import *
  File "/usr/share/fern-wifi-cracker/core/wep.py", line 8, in <module>
    from core.tools import*
  File "/usr/share/fern-wifi-cracker/core/tools.py", line 12, in <module>
    from core.toolbox import *
  File "/usr/share/fern-wifi-cracker/core/toolbox/fern_cookie_hijacker.py", line 14, in <module>
    from core.toolbox.cookie_hijacker_core import *
  File "/usr/share/fern-wifi-cracker/core/toolbox/cookie_hijacker_core.py", line 38, in <module>
    from scapy.all import *
  File "/usr/lib/python3/dist-packages/scapy/all.py", line 16, in <module>
    from scapy.arch import *
  File "/usr/lib/python3/dist-packages/scapy/arch/__init__.py", line 55, in <module>
    from scapy.arch.linux import *  # noqa F403
  File "/usr/lib/python3/dist-packages/scapy/arch/linux.py", line 27, in <module>
    from scapy.packet import Packet, Padding
  File "/usr/lib/python3/dist-packages/scapy/packet.py", line 36, in <module>
    from scapy.extlib import PYX
  File "/usr/lib/python3/dist-packages/scapy/extlib.py", line 21, in <module>
    from matplotlib import get_backend as matplotlib_get_backend
  File "/usr/lib/python3/dist-packages/matplotlib/__init__.py", line 928, in <module>
    defaultParams = rcsetup.defaultParams = {
  File "/usr/lib/python3/dist-packages/matplotlib/__init__.py", line 931, in <dictcomp>
    rcParamsDefault[key]),
  File "/usr/lib/python3/dist-packages/matplotlib/__init__.py", line 710, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'mpl_toolkits.legacy_colorbar'

**Comment by kcee02** [comment]
have you been able to get the solution?
